import assert from 'node:assert/strict';
import fs from 'node:fs';
const js=fs.readFileSync(new URL('../assets/modules/pendencias.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../assets/modules/pendencias.css',import.meta.url),'utf8');
assert.match(js,/\/api\/workflow/);
assert.match(js,/Central de Pendências/);
assert.match(js,/data-fp-route/);
assert.match(js,/FocadoPendencias/);
assert.match(js,/COCKPIT 360º DO PEDIDO/);
assert.match(js,/renderOrder360/);
assert.match(js,/data-fp-view/);
assert.match(js,/priorityFor/);
assert.match(js,/CRITICA/);
assert.match(js,/Timeline operacional/);
assert.match(js,/reactionTimeline/);
assert.match(js,/data\.reactions/);
assert.match(js,/Resolver na área responsável/);
assert.match(js,/AUTOMAÇÃO SEGURA/);
assert.match(js,/feature flag desligada por padrão/);
assert.match(css,/\.fp-page/);
assert.match(css,/\.fp360-backdrop/);
assert.match(css,/\.fp360-flow/);
assert.match(css,/\.fp-priority/);
assert.match(css,/\.fp360-timeline/);
assert.match(css,/\.fp360-event/);
assert.match(css,/\.fp-automation-status/);
assert.match(css,/@media/);
console.log('pendencias-module: ok');
