import assert from 'node:assert/strict';
import fs from 'node:fs';
const js=fs.readFileSync(new URL('../assets/modules/pendencias.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../assets/modules/pendencias.css',import.meta.url),'utf8');
assert.match(js,/\/api\/workflow/);
assert.match(js,/Central de Pendências/);
assert.match(js,/data-fp-route/);
assert.match(js,/FocadoPendencias/);
assert.match(css,/\.fp-page/);
assert.match(css,/@media/);
console.log('pendencias-module: ok');
